debug_mode: false

# Vehicle settings
vehicle_name: 'Shelby-GT 100500'
vehicle_turning_apex: 75
steering_strategy: 'tank'
accessories: []

# Video Settings
ffmpeg_command: '/usr/local/bin/ffmpeg'
ffmpeg_input_format: 'avfoundation'
ffmpeg_input_device: '0'

# Connection settings
host: '159.203.81.18'
#host: '10.4.100.59'
#host: '192.168.0.100'
port: 1337
