debug_mode: false

# Vehicle settings
vehicle_name: 'Shelby-GT 100500'
vehicle_turning_apex: 75
steering_strategy: 'tank'
accessories: []

# Video Settings
ffmpeg:
  command: '/usr/local/bin/ffmpeg'
  input_format: 'avfoundation'
  input_device: '0'
  bitrate: '800k'
  fps: 23
ratio:
  factor: 1
  horizontal: 320
  vertical: 240

# Connection settings
host: '159.203.81.18'
#host: '10.4.100.59'
#host: '192.168.0.100'
port: 1337
